[build-system]
requires = ["uv_build >= 0.12.5, <0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""

[project]
name = "lush"
version = "0.0.1"
description = "lush is a minimalist blogging platform that support rendering markdown."
readme = "README.md"
requires-python = ">=3.9,<4.0"
license = {file = "LICENSE"}
authors = [
    {name = "Eddie Aponte", email = "ed.aponte0@gmail.com"},
]

dependencies = [
    "Jinja2",
    "FastAPI",
    "SQLAlchemy",
]
